name: Auto Publish PDF Flipbook to WordPress

on:
  push:
    paths:
      - '**/*.pdf'
  workflow_dispatch:

jobs:
  post_to_wordpress:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 🔧 Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: 🔍 Detect which PDF changed
        id: detect
        run: |
          echo "Looking for changed PDF..."
          # Look at what was added/modified in this push
          PDF=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
                | grep -E '\.pdf$' | head -n1)
          # Fallback: first PDF in repo
          if [ -z "$PDF" ]; then
            PDF=$(find . -type f -name '*.pdf' | head -n1 | sed 's|^\./||')
          fi
          if [ -z "$PDF" ]; then
            echo "❌ No PDF found. Exiting."
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "✅ Will process PDF: $PDF"
            echo "found=true"  >> $GITHUB_OUTPUT
            echo "pdf=$PDF"   >> $GITHUB_OUTPUT
          fi

      - name: 🚫 Exit early if no PDF
        if: steps.detect.outputs.found == 'false'
        run: exit 0

      - name: 📝 Publish to WordPress
        env:
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: |
          FILE="${{ steps.detect.outputs.pdf }}"
          TITLE=$(basename "$FILE" .pdf | sed 's/[-_]/ /g')
          PDF_URL="$WP_SITE_URL/wp-content/uploads/$(basename "$FILE")"
          CATEGORY_NAME="Flipbook-Personal Development"

          echo "✔️ Title: $TITLE"
          echo "✔️ PDF URL: $PDF_URL"

          # Find or create category
          CAT_ID=$(curl -s "${WP_SITE_URL}/wp-json/wp/v2/categories?search=$CATEGORY_NAME" \
                    -u "$WP_USERNAME:$WP_APP_PASSWORD" \
                 | jq -r '.[0].id // empty')
          if [ -z "$CAT_ID" ]; then
            echo "➕ Creating category “$CATEGORY_NAME”"
            CAT_ID=$(curl -s -X POST "${WP_SITE_URL}/wp-json/wp/v2/categories" \
                       -u "$WP_USERNAME:$WP_APP_PASSWORD" \
                       -H "Content-Type: application/json" \
                       -d "{\"name\":\"$CATEGORY_NAME\"}" \
                    | jq -r '.id')
          fi
          echo "📂 Category ID: $CAT_ID"

          # Build post JSON
          read -r -d '' POST_JSON <<EOF
{
  "title": "$TITLE",
  "content": "📘 Read the flipbook PDF: <a href=\"$PDF_URL\">$TITLE</a>",
  "status": "publish",
  "categories": [$CAT_ID]
}
EOF

          echo "📤 Sending to WordPress…"
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "${WP_SITE_URL}/wp-json/wp/v2/posts" \
                       -u "$WP_USERNAME:$WP_APP_PASSWORD" \
                       -H "Content-Type: application/json" \
                       -d "$POST_JSON")

          BODY=$(echo "$RESPONSE" | sed '$d')
          STATUS=$(echo "$RESPONSE" | tail -n1)

          echo "🖥️ Status: $STATUS"
          echo "🖨️ Body: $BODY"

          if [ "$STATUS" -ge 400 ]; then
            echo "❌ Failed to create post"
            exit 1
          fi
          echo "✅ Post published!"
